### PR TITLE
Release 2.0-rc1

### PR DESCRIPTION
**Pull request by kevzlou7979**
## Themes 2.0
- Shorten the Module Name of each themes
  - `<inherits name="...GwtMaterialThemeBlue" />` -> `<inherits name="...ThemeBlue" />`
- Split Theme resources
- Support Dynamic Theming

### CODE REVIEW

**Comment by BenDol** [comment]
Please revert this change, I will commit my current rework changes.

**Comment by kevzlou7979** [comment]
Its just the pom.xml

**Comment by BenDol** [comment]
Ah I see, forgot i already committed haha cheers!

**Comment by kevzlou7979** [comment]
Cheers !

**Comment by kevzlou7979** [comment]
Are we going to support on 2.0 the Dynamic Theme selection or we will do it on 2.1 release?

**Comment by BenDol** [comment]
Will commit those changes now.

**Comment by kevzlou7979** [comment]
Ok great

**Comment by kevzlou7979** [comment]
I will update tomorrow the demo app about this update :) Also will test it with Errai

**Comment by kevzlou7979** [comment]
Do we have an accessibility to know what's the current color theme selected after browser refresh? Meaning if I select BLUE for example then I refresh the page, do we have some static variable stored that BLUE theme somewhere to determine the current theme. 

Example API

``` java

ThemeLoader.currentTheme();  // Will return the current theme selected and can be accessed even if we refresh the browser

```

This might be needed for specific usecase like panels or other widgets (Custom ones).

**Pull request merged**
